### ISSUE TITLE
校验执行器中验证对象（SpelValidExecutor#validateObject）内的 todo 讨论修改点

### ISSUE THREAD

**Issue by Francis200214** [stick-i/spel-validator#20]
![image](https://github.com/user-attachments/assets/3f752e3a-0307-446b-809c-e93ee03c9ef1)

这里对于 Class 的缓存，作者后续是打算在框架内部封装 Cache 功能，还是说直接引入比较主流的 Cache 框架，比如：Guava、Caffeine或Ehcache等缓存框架。
@stick-i

**Comment by stick-i** [comment]
这个todo已经被解决了，参考这个 #19 ，分支在 dev-19 的那个。

这里的缓存只是简单的 HashMap，因为程序启动后，类的字段是不会被修改的，不需要做超时之类的处理。

**Comment by Francis200214** [comment]
好的
