### ISSUE TITLE
搭建项目文档网站

### ISSUE THREAD

**Issue by stick-i** [stick-i/spel-validator#22]
使用 [VuePress](https://vuepress.vuejs.org/zh/) 框架进行搭建，此框架适用于项目说明文档，操作也比较简单，支持GitHub Page部署。

**Comment by oddfar** [comment]
可以试试这个主题：https://github.com/xugaoyi/vuepress-theme-vdoing

**Comment by stick-i** [comment]
> 可以试试这个主题：https://github.com/xugaoyi/vuepress-theme-vdoing

感觉区别不大，目前暂时不打算动文档
