### ISSUE TITLE
上传到中央仓库，maven的是什么版本

### ISSUE THREAD

**Issue by quhongwei** [stick-i/spel-validator#33]
你好， 上传到中央仓库，maven的是什么版本， 有没有遇到

下面这个错误
[INFO] --- central-publishing-maven-plugin:0.5.0:publish (injected-central-publishing) 
[WARNING] Error injecting: org.sonatype.central.publisher.plugin.PublishMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) No implementation for org.sonatype.central.publisher.client.PublisherClient was bound.
  while locating org.sonatype.central.publisher.plugin.PublishMojo

1 error

**Comment by stick-i** [comment]
没有遇到你这个问题。

能说说你这个问题的背景吗？貌似你这个问题与本项目并没有什么关系？

**Comment by stick-i** [comment]
由于该issue太久没有活跃，我先将它关闭了
