### ISSUE TITLE
支持jakarta.validation

### ISSUE THREAD

**Issue by i1619khz** [stick-i/spel-validator#36]
希望加上jakarta.validation的支持，目前我在使用springboot3和quarkus，javax全部改成了jakarta，希望提供支持

**Comment by stick-i** [comment]
可以的。我放到任务里。

理论上来说，你的项目里可以同时引入javax和jakarta的包，这样应该可以支持你暂且用着。后续我升级了之后，你只需要对pom依赖应该替换就可以了。

**Comment by stick-i** [comment]
如果你有兴趣成为该项目的贡献者，也可以交由你来完成这个任务😀。

**Comment by i1619khz** [comment]
@stick-i 问题不大，提供两套实现应该是可以的，分为core，javax，jakarta

**Comment by stick-i** [comment]
> @stick-i 问题不大，提供两套实现应该是可以的，分为core，javax，jakarta

看起来应该是这么个做法，包名取为类似spel-validator-javax就好了。


你有兴趣来尝试完成它吗？
或者我将它放在下下个版本自己来完成，大概会在下周发布。
