### ISSUE TITLE
请教一个spel 参数在idea 中关联的问题

### ISSUE THREAD

**Issue by su-yh** [stick-i/spel-validator#39]
![](https://forum.springdoc.cn/uploads/default/optimized/2X/c/c0dcafa6a3377733c695b721d452016d1348bf4d_2_690x416.png)

上图是我自实现的注解，并且对注解的 value 参数添加了 idea 提供的 @Language(“SpEL”) 注解，所以它能识别到是spel 表达式。但是参数 #loginUser 以及 #opt 却无法识别到。

![](https://forum.springdoc.cn/uploads/default/optimized/2X/e/ea7320760499b184aee39668da72c76f5a9f04d7_2_690x248.png)

这个是SpringSecurity 提供的 注解，它能识别到spel 表达式，同时还能识别到方法参数，通过鼠标还能点击跳转。

如何才能做到像SpringSecurity 那样，让idea 识别到spel 表达式中的参数，并且点击能跳转到参数具体的位置。

Language(“SpEL”) 注解  也是看到项目中用到，才学到的，所以想来问下。  ^_^

**Comment by helloAping** [comment]
这个可能得自定义idea规则，或者插件实现

**Comment by stick-i** [comment]
woc，这个issue居然来自两周以前，不好意思，我之前是真没看到，不然肯定会回复你的🥲
-----
这个应该是需要插件支持的，idea里应该默认有安装SpringSecurity的插件。

**Comment by su-yh** [comment]
> woc，这个issue居然来自两周以前，不好意思，我之前是真没看到，不然肯定会回复你的🥲
> 
> 这个应该是需要插件支持的，idea里应该默认有安装SpringSecurity的插件。

好的，谢谢。我再找找看，如果idea 默认安装 了SpringSecurity 的插件的话，我看下那个插件要怎么使用或者配置。

**Comment by su-yh** [comment]
> 这个可能得自定义idea规则，或者插件实现

好的谢谢。我再找找看。

**Comment by su-yh** [comment]
nothing
